version: '2'

services:
  code:
    container_name: uploader_code
    image: debian
    volumes:
      - ./:/var/www/app

  data:
    container_name: uploader_data
    image: debian
    volumes:
      - .docker/uploader_mysql:/var/lib/mysql
      - .docker/uploader_data:/data

  php-fpm:
    container_name: uploader_php-fpm
    restart: always
    image: vinhnguyen1512/laravel-php-fpm
    volumes_from:
      - code
    expose:
      - "9000"
    links:
      - workspace

  nginx:
    container_name: uploader_nginx
    restart: always
    image: nginx
    volumes_from:
      - data
      - code
    volumes:
      - ./.nginx/conf.d:/etc/nginx/conf.d
    ports:
      - "8000:80"
    links:
      - php-fpm

  mysql:
    container_name: uploader_mysql
    restart: always
    image: mysql
    volumes_from:
      - data
    expose:
      - "3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

  redis:
    container_name: uploader_redis
    restart: always
    image: redis
    expose:
      - "6379"
    volumes_from:
      - data

  workspace:
    container_name: uploader_workspace
    restart: always
    image: vinhnguyen1512/laravel-workspace
    volumes_from:
      - code
    tty: true
